{% set name = "pixi-kernel" %}
{% set version = "0.2.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 1f15ba525a51d216470a1207470bd12279e8e262b10e82a9f70e92bed9f73c01

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - hatchling
    - pip
  run:
    - python >=3.8,<4.0
    - jupyter_client >=7
    - msgspec >=0.18

test:
  imports:
    - pixi_kernel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/renan-r-santos/pixi-kernel
  summary: Jupyter kernel using Pixi for reproducible notebooks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - renan-r-santos
