{% set name = "pixi-kernel" %}
{% set version = "0.1.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pixi-kernel-{{ version }}.tar.gz
  sha256: fdf9c5e21a40cf4a5919d3b8831e0ca1610d781a47a2b5d3ff4d4d1f812a024d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - setuptools
    - pip
  run:
    - python >=3.8,<4.0
    - ipykernel >=6,<7
    - msgspec >=0.18,<1

test:
  imports:
    - pixi_kernel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/renan-r-santos/pixi-kernel
  summary: Python Jupyter kernel using Pixi for reproducible notebooks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - renan-r-santos
