{% set name = "pixi-kernel" %}
{% set version = "0.5.3" %}
{% set python_min = "3.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pixi_kernel-{{ version }}.tar.gz
  sha256: 79b4dbcab688feb9fd919286438333dc12baaa329179260c2af8ee1a959a692e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - jupyter_client >=7
    - pydantic >=2,<3

test:
  imports:
    - pixi_kernel
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/renan-r-santos/pixi-kernel
  summary: Jupyter kernels using Pixi for reproducible notebooks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - renan-r-santos
