{% set name = "pixi-kernel" %}
{% set version = "0.5.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/pixi_kernel-{{ version }}.tar.gz
  sha256: f8be9b93f6f880bd964edf8a2ea613ea904ed79fefbb41ad14224cdeb620306a

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8,<4.0
    - hatchling
    - pip
  run:
    - python >=3.9,<4.0
    - jupyter_client >=7
    - pydantic >=2,<3

test:
  imports:
    - pixi_kernel
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/renan-r-santos/pixi-kernel
  summary: Jupyter kernels using Pixi for reproducible notebooks
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - renan-r-santos
